services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend/frontend
      dockerfile: ../Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/frontend/src:/app/src
    depends_on:
      - backend

  # mcp:
  #   build:
  #     context: ./mcp_server
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - ./mcp_server:/app
  #     - ./backend/app/data:/shared_data
  #   env_file:
  #     - .env
  #   depends_on:
  #     - backend
